version: "3.8"

services:
  jenkins:
    image: whanos-jenkins
    restart: unless-stopped
    environment:
      - ADMIN_PASSWORD=password
      - DOCKER_HOST=tcp://docker:2375
    ports:
      - 8080:8080
    depends_on:
      - docker
  docker:
    image: docker:dind
    restart: unless-stopped
    privileged: true
    ports:
      - 2375:2375
    environment:
     - DOCKER_TLS_CERTDIR=