FROM esolang/befunge93

# using bash shell
SHELL ["/bin/bash", "-c"]
# copying all current directory files in the docker
ONBUILD COPY . /app
# going to /app
ONBUILD WORKDIR /app
# running the befunge file
ONBUILD CMD befunge93 app/main.bf