apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind-image
        image: docker:dind
        ports:
        - containerPort: 2375
        env:
          - name: DOCKER_TLS_CERTDIR
            value: ""
        securityContext:
          privileged: true
      restartPolicy: Always