apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-image
        image: europe-west1-docker.pkg.dev/plucky-agency-332314/whanos/jenkins
        ports:
        - name: web-page
          containerPort: 8080
        env:
          - name: ADMIN_PASSWORD
            value: "password"
          - name: DOCKER_HOST
            value: "tcp://10.0.6.237:2375"
      restartPolicy: Always