kind: Service
apiVersion: v1
metadata:
  name:  jenkins-service
spec:
  selector:
    app:  jenkins
  type:  LoadBalancer
  ports:
  - name:  http-web-page
    port:  8080
    protocol: TCP
    targetPort:  web-page