FROM node:14.17.5-alpine

# install bash
RUN apk add --no-cache bash
# using bash shell
SHELL ["/bin/bash", "-c"]
# copying all worker files in the docker
ONBUILD COPY . /app
# going to /app
ONBUILD WORKDIR /app
# Install app dependencies
ONBUILD RUN npm install --production=false
# run the application
ONBUILD CMD [ "node", "." ]